// city_district_data.dart

const List<String> iller = [
  'Adana', 'Adıyaman', 'Afyonkarahisar', 'Ağrı', 'Aksaray',
  'Amasy', 'Ankara', 'Antalya', 'Ardahan', 'Artvin',
  'Aydın', 'Balıkesir', 'Bartın', 'Batman', 'Bayburt',
  'Bilecik', 'Bingöl', 'Bitlis', 'Bolu', 'Burdur',
  'Bursa', 'Çanakkale', 'Çankırı', 'Çorum', 'Denizli',
  'Diyarbakır', 'Düzce', 'Edirne', 'Elazığ', 'Erzincan',
  'Erzurum', 'Eskişehir', 'Gaziantep', 'Giresun', 'Gümüşhane',
  'Hakkari', 'Hatay', 'Iğdır', 'Isparta', 'İstanbul',
  'İzmir', 'Kahramanmaraş', 'Karabük', 'Karaman', 'Kars',
  'Kastamonu', 'Kayseri', 'Kırıkkale', 'Kırklareli', 'Kırşehir',
  'Kilis', 'Kocaeli', 'Konya', 'Kütahya', 'Malatya',
  'Manisa', 'Mardin', 'Mersin', 'Muğla', 'Muş',
  'Nevşehir', 'Niğde', 'Ordu', 'Osmaniye', 'Rize',
  'Sakarya', 'Samsun', 'Siirt', 'Sinop', 'Sivas',
  'Şanlıurfa', 'Şırnak', 'Tekirdağ', 'Tokat', 'Trabzon',
  'Tunceli', 'Uşak', 'Van', 'Yalova', 'Yozgat',
  'Zonguldak'
];

const Map<String, List<String>> ilceler = {
  'Adana': ['Seyhan', 'Çukurova', 'Yüreğir', 'Sarıçam', 'Ceyhan', 'Karaisalı', 'İmamoğlu', 'Pozantı', 'Feke', 'Aladağ', 'Saimbeyli', 'Tufanbeyli'],
  'Adıyaman': ['Merkez', 'Besni', 'Kahta', 'Gölbaşı', 'Çelikhan', 'Samsat', 'Sincik', 'Tut'],
  'Afyonkarahisar': ['Merkez', 'Sandıklı', 'Dinar', 'Emirdağ', 'Bolvadin', 'Çay', 'Sultandağı', 'İhsaniye', 'Başmakçı', 'Evciler', 'Hocalar', 'Sinanpaşa', 'Şuhut'],
  'Ağrı': ['Merkez', 'Doğubayazıt', 'Patnos', 'Hamur', 'Taşlıçay', 'Tutak', 'Diyadin'],
  'Aksaray': ['Merkez', 'Eskil', 'Gülağaç', 'Ortaköy', 'Ağaçören', 'Sarıyahşi'],
  'Amasya': ['Merkez', 'Suluova', 'Gümüşhacıköy', 'Taşova', 'Göynücek', 'Merzifon'],
  'Ankara': ['Çankaya', 'Keçiören', 'Mamak', 'Altındağ', 'Yenimahalle', 'Sincan', 'Etimesgut', 'Pursaklar', 'Gölbaşı', 'Beypazarı', 'Nallıhan', 'Kızılcahamam', 'Çubuk', 'Ayaş', 'Elmadağ', 'Kalecik', 'Şereflikoçhisar', 'Akyurt'],
  'Antalya': ['Muratpaşa', 'Konyaaltı', 'Alanya', 'Manavgat', 'Serik', 'Kepez', 'Aksu', 'Döşemealtı', 'Finike', 'Kemer', 'Kaş', 'Demre', 'Elmalı', 'Gazipaşa'],
  'Ardahan': ['Merkez', 'Göle', 'Çıldır', 'Hanak', 'Posof'],
  'Artvin': ['Merkez', 'Hopa', 'Arhavi', 'Borçka', 'Murgul', 'Şavşat', 'Yusufeli'],
  'Aydın': ['Merkez', 'Efeler', 'Nazilli', 'Söke', 'Didim', 'Kuşadası', 'Çine', 'Germencik', 'Bozdoğan', 'Koçarlı', 'İncirliova', 'Karpuzlu', 'Buharkent', 'Karacasu', 'Sultanhisar', 'Köşk', 'Bayındır', 'Gölmarmara', 'Koçarlı'],
  'Balıkesir': ['Merkez', 'Karesi', 'Altıeylül', 'Edremit', 'Bandırma', 'Susurluk', 'Bigadiç', 'Dursunbey', 'Erdek', 'Manyas', 'Savaştepe', 'Gönen', 'Burhaniye', 'Sındırgı', 'İvrindi', 'Marmara', 'Ayvalık'],
  'Bartın': ['Merkez', 'Ulus', 'Kurucaşile', 'Amasra'],
  'Batman': ['Merkez', 'Kozluk', 'Sason', 'Beşiri'],
  'Bayburt': ['Merkez', 'Aydıntepe', 'Demirözü'],
  'Bilecik': ['Merkez', 'Bozüyük', 'Osmaneli', 'Pazaryeri', 'Söğüt', 'Gölpazarı', 'İnhisar'],
  'Bingöl': ['Merkez', 'Genç', 'Solhan', 'Kiğı', 'Adaklı', 'Yayladere', 'Yedisu'],
  'Bitlis': ['Merkez', 'Tatvan', 'Ahlat', 'Hizan', 'Mutki', 'Güroymak'],
  'Bolu': ['Merkez', 'Gerede', 'Dörtdivan', 'Mudurnu', 'Seben', 'Mengen', 'Yeniçağa', 'Kıbrısçık'],
  'Burdur': ['Merkez', 'Bucak', 'Gölhisar', 'Tefenni', 'Yeşilova', 'Ağlasun', 'Karamanlı', 'Altınyayla', 'Çavdır'],
  'Bursa': ['Osmangazi', 'Yıldırım', 'Nilüfer', 'İnegöl', 'Gemlik', 'Orhangazi', 'Mudanya', 'Karacabey', 'Kestel', 'Mustafakemalpaşa', 'Harmancık', 'Yenişehir', 'Keles', 'Gürsu'],
  'Çanakkale': ['Merkez', 'Eceabat', 'Biga', 'Çan', 'Lapseki', 'Ezine', 'Bayramiç', 'Gelibolu', 'Gökçeada', 'Bozcaada'],
  'Çankırı': ['Merkez', 'Kurşunlu', 'Orta', 'Çerkeş', 'Korgun', 'Yapraklı', 'Atkaracalar', 'Ilgaz', 'Eldivan', 'Bayramören'],
  'Çorum': ['Merkez', 'Osmancık', 'Sungurlu', 'Alaca', 'Bayat', 'İskilip', 'Kargı', 'Mecitözü', 'Ortaköy', 'Uğurludağ', 'Laçin', 'Boğazkale', 'Dodurga', 'Oğuzlar'],
  'Denizli': ['Merkezefendi', 'Pamukkale', 'Acıpayam', 'Buldan', 'Çal', 'Çardak', 'Bekilli', 'Baklan', 'Serinhisar', 'Tavas', 'Honaz', 'Babadağ', 'Sarayköy', 'Kale'],
  'Diyarbakır': ['Bağlar', 'Kayapınar', 'Yenişehir', 'Sur', 'Silvan', 'Bismil', 'Çınar', 'Kulp', 'Lice', 'Hazro', 'Eğil', 'Hani', 'Dicle', 'Kocaköy'],
  'Düzce': ['Merkez', 'Akçakoca', 'Yığılca', 'Cumayeri', 'Gölyaka', 'Çilimli', 'Kaynaşlı'],
  'Edirne': ['Merkez', 'Uzunköprü', 'Keşan', 'İpsala', 'Meriç', 'Lalapaşa', 'Havsa'],
  'Elazığ': ['Merkez', 'Maden', 'Karakoçan', 'Kovancılar', 'Baskil', 'Arıcak', 'Alacakaya', 'Sivrice', 'Ağın', 'Harput'],
  'Erzincan': ['Merkez', 'Tercan', 'Çayırlı', 'Refahiye', 'İliç', 'Otlukbeli', 'Kemah', 'Kemaliye', 'Üzümlü'],
  'Erzurum': ['Yakutiye', 'Palandöken', 'Aziziye', 'Oltu', 'Pasinler', 'İspir', 'Hınıs', 'Karaçoban', 'Narman', 'Olur', 'Tortum', 'Uzundere', 'Horasan', 'Şenkaya', 'Aşkale', 'Tekman', 'Çat'],
  'Eskişehir': ['Odunpazarı', 'Tepebaşı', 'Sivrihisar', 'Çifteler', 'Alpu', 'Mihalıççık', 'Sarıcakaya', 'Seyitgazi', 'İnönü', 'Mahmudiye'],
  'Gaziantep': ['Şahinbey', 'Şehitkamil', 'Nizip', 'Araban', 'İslahiye', 'Karkamış', 'Yavuzeli', 'Oğuzeli'],
  'Giresun': ['Merkez', 'Espiye', 'Eynesil', 'Görele', 'Piraziz', 'Tirebolu', 'Dereli', 'Yağlıdere', 'Çanakçı', 'Alucra', 'Keşap'],
  'Gümüşhane': ['Merkez', 'Kelkit', 'Şiran', 'Torul', 'Köse'],
  'Hakkari': ['Merkez', 'Şemdinli', 'Yüksekova', 'Çukurca'],
  'Hatay': ['Antakya', 'İskenderun', 'Defne', 'Dörtyol', 'Kırıkhan', 'Reyhanlı', 'Samandağ', 'Erzin', 'Payas', 'Hassa', 'Yayladağı', 'Arsuz'],
  'Iğdır': ['Merkez', 'Tuzluca', 'Aralık', 'Karakoyunlu'],
  'Isparta': ['Merkez', 'Eğirdir', 'Yalvaç', 'Senirkent', 'Gönen', 'Şarkikaraağaç', 'Uluborlu', 'Atabey', 'Sütçüler', 'Keçiborlu', 'Aksu'],
  'İstanbul': ['Adalar', 'Bakırköy', 'Beşiktaş', 'Beylikdüzü', 'Beyoğlu', 'Çatalca', 'Esenler', 'Esenyurt', 'Eyüpsultan', 'Fatih', 'Gaziosmanpaşa', 'Kadıköy', 'Kağıthane', 'Kartal', 'Maltepe', 'Pendik', 'Sancaktepe', 'Sarıyer', 'Şile', 'Şişli', 'Sultanbeyli', 'Sultangazi', 'Tuzla', 'Ümraniye', 'Üsküdar', 'Zeytinburnu'],
  'İzmir': ['Konak', 'Karşıyaka', 'Bornova', 'Buca', 'Gaziemir', 'Balçova', 'Bayraklı', 'Çiğli', 'Aliağa', 'Foça', 'Karaburun', 'Seferihisar', 'Selçuk', 'Urla', 'Menderes', 'Torbalı', 'Kemalpaşa', 'Dikili', 'Bergama', 'Ödemiş', 'Tire', 'Bayındır', 'Kınık'],
  'Kahramanmaraş': ['Onikişubat', 'Dulkadiroğlu', 'Elbistan', 'Afşin', 'Göksun', 'Pazarcık', 'Andırın', 'Çağlayancerit', 'Ekinözü', 'Nurhak'],
  'Karabük': ['Merkez', 'Eskipazar', 'Ovacık', 'Yenice'],
  'Karaman': ['Merkez', 'Ermenek', 'Kazımkarabekir', 'Ayrancı'],
  'Kars': ['Merkez', 'Kağızman', 'Sarıkamış', 'Akyaka', 'Digor', 'Arpaçay'],
  'Kastamonu': ['Merkez', 'Taşköprü', 'Tosya', 'Küre', 'Cide', 'İnebolu', 'Azdavay', 'Devrekani', 'Pınarbaşı', 'Doğanyurt', 'Seydiler', 'İhsangazi', 'Şenpazar', 'Abana', 'Bozkurt', 'Araç'],
  'Kayseri': ['Kocasinan', 'Melikgazi', 'Talas', 'Develi', 'İncesu', 'Hacılar', 'Bünyan', 'Tomarza', 'Sarız', 'Felahiye', 'Yeşilhisar', 'Özvatan', 'Pınarbaşı', 'Sarıoğlan', 'Talas', 'Yahyalı'],
  'Kırıkkale': ['Merkez', 'Bahşili', 'Sulakyurt', 'Delice', 'Karakeçili', 'Keskin'],
  'Kırklareli': ['Merkez', 'Lüleburgaz', 'Vize', 'Babaeski', 'Demirköy', 'Pehlivanköy', 'Kofçaz'],
  'Kırşehir': ['Merkez', 'Mucur', 'Çiçekdağı', 'Kaman'],
  'Kilis': ['Merkez', 'Elbeyli', 'Musabeyli', 'Polateli'],
  'Kocaeli': ['İzmit', 'Gebze', 'Çayırova', 'Darıca', 'Derince', 'Körfez', 'Gölcük', 'Kandıra', 'Başiskele'],
  'Konya': ['Selçuklu', 'Meram', 'Karatay', 'Ilgın', 'Kadınhanı', 'Ereğli', 'Seydişehir', 'Beyşehir', 'Bozkır', 'Çumra', 'Akşehir', 'Hadim', 'Taşkent', 'Yunak', 'Derebucak', 'Halkapınar', 'Sarayönü', 'Doğanhisar', 'Altınekin', 'Cihanbeyli', 'Kadınhanı'],
  'Kütahya': ['Merkez', 'Simav', 'Tavşanlı', 'Domaniç', 'Emet', 'Altıntaş', 'Dumlupınar', 'Şaphane', 'Gediz', 'Aslanapa', 'Pazarlar'],
  'Malatya': ['Battalgazi', 'Yeşilyurt', 'Kuluncak', 'Pütürge', 'Doğanşehir', 'Hekimhan', 'Arapgir', 'Darende', 'Yazıhan', 'Arguvan'],
  'Manisa': ['Yunusemre', 'Şehzadeler', 'Turgutlu', 'Salihli', 'Akhisar', 'Kırkağaç', 'Sarıgöl', 'Demirci', 'Alaşehir', 'Gördes', 'Kula', 'Soma', 'Selendi', 'Saruhanlı', 'Gölmarmara', 'Tire'],
  'Mardin': ['Artuklu', 'Derik', 'Midyat', 'Nusaybin', 'Savur', 'Dargeçit', 'Kızıltepe'],
  'Mersin': ['Akdeniz', 'Mezitli', 'Toroslar', 'Yenişehir', 'Erdemli', 'Silifke', 'Mut', 'Tarsus', 'Çamlıyayla', 'Aydıncık', 'Bozyazı', 'Gülnar'],
  'Muğla': ['Menteşe', 'Fethiye', 'Ortaca', 'Bodrum', 'Datça', 'Seydikemer', 'Yatağan', 'Dalaman', 'Ula', 'Köyceğiz', 'Marmaris'],
  'Muş': ['Merkez', 'Malazgirt', 'Bulanık', 'Varto'],
  'Nevşehir': ['Merkez', 'Ürgüp', 'Avanos', 'Gülşehir', 'Derinkuyu', 'Hacıbektaş'],
  'Niğde': ['Merkez', 'Bor', 'Çamardı', 'Altunhisar'],
  'Ordu': ['Altınordu', 'Fatsa', 'Ünye', 'Perşembe', 'Gölköy', 'Korgan', 'Kabataş', 'Gülyalı', 'Çamaş', 'Akkuş', 'Mesudiye', 'Ulubey', 'Çatalpınar', 'Çaybaşı', 'Kumru'],
  'Osmaniye': ['Merkez', 'Kadirli', 'Düziçi', 'Bahçe', 'Hasanbeyli', 'Sumbas', 'Toprakkale'],
  'Rize': ['Merkez', 'Ardeşen', 'Fındıklı', 'Çayeli', 'Pazar', 'İkizdere', 'İyidere', 'Kalkandere', 'Güneysu'],
  'Sakarya': ['Adapazarı', 'Serdivan', 'Erenler', 'Karasu', 'Akyazı', 'Hendek', 'Sapanca', 'Geyve', 'Kaynarca', 'Pamukova', 'Ferizli', 'Kocaali', 'Taraklı'],
  'Samsun': ['Atakum', 'Canik', 'İlkadım', 'Bafra', 'Çarşamba', 'Havza', 'Terme', 'Vezirköprü', 'Asarcık', 'Ladik', 'Salıpazarı', 'Tekkeköy', 'Kavak', 'Ayvacık', 'Ondokuzmayıs'],
  'Siirt': ['Merkez', 'Eruh', 'Pervari', 'Şirvan', 'Kurtalan'],
  'Sinop': ['Merkez', 'Durağan', 'Boyabat', 'Türkeli', 'Erfelek', 'Ayancık', 'Gerze'],
  'Sivas': ['Merkez', 'Divriği', 'Kangal', 'Yıldızeli', 'Şarkışla', 'Gürün', 'Zara', 'Altınyayla', 'Koyulhisar', 'Suşehri', 'Akıncılar', 'Gemerek', 'Hafik', 'İmranlı'],
  'Şanlıurfa': ['Eyyübiye', 'Haliliye', 'Karaköprü', 'Siverek', 'Birecik', 'Bozova', 'Ceylanpınar', 'Hilvan', 'Suruç', 'Viranşehir', 'Halfeti'],
  'Şırnak': ['Merkez', 'Silopi', 'Cizre', 'İdil', 'Beytüşşebap', 'Uludere'],
  'Tekirdağ': ['Süleymanpaşa', 'Çerkezköy', 'Çorlu', 'Malkara', 'Muratlı', 'Hayrabolu', 'Kapaklı', 'Şarköy'],
  'Tokat': ['Merkez', 'Almus', 'Reşadiye', 'Turhal', 'Zile', 'Erbaa', 'Pazar', 'Artova', 'Niksar', 'Başçiftlik', 'Sulusaray'],
  'Trabzon': ['Ortahisar', 'Akçaabat', 'Araklı', 'Arsin', 'Beşikdüzü', 'Çarşıbaşı', 'Çaykara', 'Dernekpazarı', 'Düzköy', 'Hayrat', 'Köprübaşı', 'Maçka', 'Of', 'Sürmene', 'Şalpazarı', 'Tonya', 'Vakfıkebir', 'Yomra'],
  'Tunceli': ['Merkez', 'Nazımiye', 'Ovacık', 'Pertek', 'Pülümür', 'Çemişgezek', 'Hozat', 'Mazgirt'],
  'Uşak': ['Merkez', 'Banaz', 'Eşme', 'Sivaslı', 'Ulubey'],
  'Van': ['İpekyolu', 'Edremit', 'Tuşba', 'Erciş', 'Çatak', 'Muradiye', 'Bahçesaray', 'Özalp', 'Saray', 'Gürpınar'],
  'Yalova': ['Merkez', 'Çınarcık', 'Altınova', 'Armutlu', 'Termal'],
  'Yozgat': ['Merkez', 'Sorgun', 'Yerköy', 'Akdağmadeni', 'Sarıkaya', 'Boğazlıyan', 'Çayıralan', 'Kadışehri', 'Saraykent', 'Aydıncık', 'Çandır'],
  'Zonguldak': ['Merkez', 'Ereğli', 'Çaycuma', 'Devrek', 'Alaplı', 'Gökçebey']
};
