// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIj_CrFjfNVRvvJTukTwLAbe-HJmm-VfU',
    appId: '1:738256828606:web:fa78fcab9a284d12e846ef',
    messagingSenderId: '738256828606',
    projectId: 'depsis-project-ffbe2',
    authDomain: 'depsis-project-ffbe2.firebaseapp.com',
    storageBucket: 'depsis-project-ffbe2.firebasestorage.app',
    measurementId: 'G-GPTKRQ368P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFmVMGOzB6Tp41xz8uwjwwmSTjdkijo-g',
    appId: '1:738256828606:android:3201643c4ec00658e846ef',
    messagingSenderId: '738256828606',
    projectId: 'depsis-project-ffbe2',
    storageBucket: 'depsis-project-ffbe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB7M5mJ7kUNblXNDNQmB-LEEx_9WoGi1k',
    appId: '1:738256828606:ios:6d6d3e2e5b97fce3e846ef',
    messagingSenderId: '738256828606',
    projectId: 'depsis-project-ffbe2',
    storageBucket: 'depsis-project-ffbe2.firebasestorage.app',
    iosBundleId: 'com.example.depsisProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB7M5mJ7kUNblXNDNQmB-LEEx_9WoGi1k',
    appId: '1:738256828606:ios:6d6d3e2e5b97fce3e846ef',
    messagingSenderId: '738256828606',
    projectId: 'depsis-project-ffbe2',
    storageBucket: 'depsis-project-ffbe2.firebasestorage.app',
    iosBundleId: 'com.example.depsisProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIj_CrFjfNVRvvJTukTwLAbe-HJmm-VfU',
    appId: '1:738256828606:web:69c87ca712ab6d32e846ef',
    messagingSenderId: '738256828606',
    projectId: 'depsis-project-ffbe2',
    authDomain: 'depsis-project-ffbe2.firebaseapp.com',
    storageBucket: 'depsis-project-ffbe2.firebasestorage.app',
    measurementId: 'G-9H1TMMBT5J',
  );

}